apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: k8s-windhigh-com-tls
spec:
  secretName: k8s-windhigh-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.windhigh.com
  dnsNames:
    - k8s.windhigh.com
    - www.k8s.windhigh.com